[package]
name = "bevy-hud-pass"
version = "0.1.0"
authors = ["Robert Swain <robert.swain@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
bevy = "0.5"

[dev-dependencies]
bevy_fly_camera = "0.7.0"